### ISSUE TITLE
Harvesting from Regione Toscana

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#157] opened 2018-03-06 09:48 UTC
We need to perform again the harvest test for the following harvest source since the previous issues should be fixed now in the remote catalog:

- Regione Toscana: http://dati.toscana.it/catalog.rdf

**Comment by etj** [comment] 2018-03-06 14:56
![ckan101](https://user-images.githubusercontent.com/717359/37039013-ae26f31c-2156-11e8-8801-a0e0b8ba9fc4.png)

Since publisher is 0..1, the errors related to the publisher name and publisher id should be investigated.

**Comment by cezio** [comment] 2018-03-12 21:57
part of this should be fixed with #163

**Comment by cezio** [comment] 2018-03-16 20:16
Guys, please check if fixes from #163 removes those errors. Also, is this overlaps with #150?

**Comment by etj** [comment] 2018-03-19 16:09
@cezio no overlaps. #155 refers to new sources not previously harvested.

**Comment by etj** [comment] 2018-03-21 09:39
New harvesting results:

![jobreport](https://user-images.githubusercontent.com/717359/37702841-1c78cd88-2cf4-11e8-89b9-d410f8cfb6a7.png)

**Comment by etj** [comment] 2018-03-21 14:14
Blocked by
- #168 
- #169

**Comment by etj** [comment] 2018-03-27 09:12
The only remaining errors are caused by bad dataset content:

![toscana](https://user-images.githubusercontent.com/717359/37958028-ad654190-31af-11e8-939b-2fba70b2c847.png)

**Comment by etj** [comment] 2018-03-27 09:13
The only errors are caused by bad source datasets:

![toscana](https://user-images.githubusercontent.com/717359/37958081-d0875852-31af-11e8-996e-9f61efdee717.png)

**Closed** 2018-04-04 16:04 UTC
Labels: AgID, P: Medium, Support Contract, Test, task
